# Generated by Django 5.2.3 on 2025-06-28 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_user_email'),
        ('api', '0004_producto_descripcion'),
    ]

    operations = [
    ]
