# Generated by Django 5.2.3 on 2025-06-29 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_carrito_itemcarrito'),
        ('api', '0005_merge_0004_alter_user_email_0004_producto_descripcion'),
    ]

    operations = [
    ]
