# Generated by Django 5.2.3 on 2025-06-30 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_producto_imagen_orden_itemorden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
